// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDufbJ5NUA9p0I3wRxqEKT19Z4H_Wc4Sr4',
    appId: '1:646967698939:web:ff43ebef396e335a468b9e',
    messagingSenderId: '646967698939',
    projectId: 'simpleshop1-11be8',
    authDomain: 'simpleshop1-11be8.firebaseapp.com',
    storageBucket: 'simpleshop1-11be8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDufbJ5NUA9p0I3wRxqEKT19Z4H_Wc4Sr4',
    appId: '1:646967698939:android:ff43ebef396e335a468b9e',
    messagingSenderId: '646967698939',
    projectId: 'simpleshop1-11be8',
    storageBucket: 'simpleshop1-11be8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDufbJ5NUA9p0I3wRxqEKT19Z4H_Wc4Sr4',
    appId: '1:646967698939:ios:ff43ebef396e335a468b9e',
    messagingSenderId: '646967698939',
    projectId: 'simpleshop1-11be8',
    storageBucket: 'simpleshop1-11be8.appspot.com',
    iosBundleId: 'com.example.simpleshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDufbJ5NUA9p0I3wRxqEKT19Z4H_Wc4Sr4',
    appId: '1:646967698939:macos:ff43ebef396e335a468b9e',
    messagingSenderId: '646967698939',
    projectId: 'simpleshop1-11be8',
    storageBucket: 'simpleshop1-11be8.appspot.com',
    iosBundleId: 'com.example.simpleshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDufbJ5NUA9p0I3wRxqEKT19Z4H_Wc4Sr4',
    appId: '1:646967698939:windows:ff43ebef396e335a468b9e',
    messagingSenderId: '646967698939',
    projectId: 'simpleshop1-11be8',
    authDomain: 'simpleshop1-11be8.firebaseapp.com',
    storageBucket: 'simpleshop1-11be8.appspot.com',
  );
}
